version: '2'
services:
  db:
    image: mdillon/postgis
    ports:
      - "5433:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
